version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5151:5151"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "5152:5152"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bugatube
      - JWT_SECRET=your_jwt_secret
    volumes:
      - /nvmestorage/bugatube/uploads:/app/uploads
    devices:
      - /dev/dri:/dev/dri
    networks:
      - bugatube-network
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - /nvmestorage/bugatube/mongo-data:/data/db
    networks:
      - bugatube-network
networks:
  bugatube-network:
    driver: bridge
